apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - harbor-external-secret.yaml
  - openwebui-external-secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: harbor.gnzaga.com/library/portfolio-website
    newTag: latest
