apiVersion: v1
kind: Service
metadata:
  name: portfolio-website
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  selector:
    app: portfolio-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
